CREATE DATABASE IF NOT EXISTS ShopDB;
USE ShopDB;


CREATE TABLE IF NOT EXISTS GeoIPCache (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IPRange VARCHAR(50),
    CountryID INT
) ENGINE=MEMORY;


CREATE TABLE IF NOT EXISTS ProductDescription (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Description TEXT,
    ProductID INT,
    CountryID INT,
    FOREIGN KEY (CountryID) REFERENCES Countries(ID)
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Logs (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Timestamp DATETIME,
    Message TEXT
) ENGINE=BLACKHOLE;


CREATE TABLE IF NOT EXISTS ProductReporting (
    Date DATE,
    ProductName VARCHAR(100),
    Orders INT
) ENGINE=CSV;
